### ISSUE TITLE
"DiscordError" at launch (since Krita 5.2.3, it seems)

### ISSUE THREAD

**Issue by tocram1** [Firstbober/Krita-rpc#11]
Since I updated to Krita 5.2.3, I get this error at launch :

```
DiscordError
Python 3.10.7: C:\Program Files\Krita (x64)\bin\krita.exe
Tue Aug 27 23:35:07 2024

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 C:\Users\Théo\AppData\Roaming\krita\pykrita\discord_rpc\discord_rpc.py in setup(self=<discord_rpc.discord_rpc.DiscordRpc object>)
   22 
   23     def setup(self):
   24         RPC.connect()  # Start the handshake loop
   25         self.timer.start()
   26 
global RPC = <discord_rpc.presence.Presence object>
RPC.connect = <bound method Presence.connect of <discord_rpc.presence.Presence object>>

 C:\Users\Théo\AppData\Roaming\krita\pykrita\discord_rpc\presence.py in connect(self=<discord_rpc.presence.Presence object>)
   43     def connect(self):
   44         self.update_event_loop(get_event_loop())
   45         self.loop.run_until_complete(self.handshake())
   46 
   47     def close(self):
self = <discord_rpc.presence.Presence object>
self.loop = <ProactorEventLoop running=False closed=False debug=False>
self.loop.run_until_complete = <bound method BaseEventLoop.run_until_complete o...ventLoop running=False closed=False debug=False>>
self.handshake = <bound method BaseClient.handshake of <discord_rpc.presence.Presence object>>

 C:\Program Files\Krita (x64)\asyncio\base_events.py in run_until_complete(self=<ProactorEventLoop running=False closed=False debug=False>, future=<Task finished name='Task-1' coro=<BaseClient.ha...r('Error Code: 4000 Message: Invalid Client ID')>)


 C:\Users\Théo\AppData\Roaming\krita\pykrita\discord_rpc\baseclient.py in handshake(self=<discord_rpc.presence.Presence object>)
  119         data = json.loads(await self.sock_reader.read(length))
  120         if 'code' in data:
  121             raise DiscordError(data['code'], data['message'])
  122         if self._events_on:
  123             self.sock_reader.feed_data = self.on_event
global DiscordError = <class 'discord_rpc.exceptions.DiscordError'>
data = {'code': 4000, 'message': 'Invalid Client ID'}
DiscordError: Error Code: 4000 Message: Invalid Client ID
    __cause__ = None
    __class__ = <class 'discord_rpc.exceptions.DiscordError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of DiscordError object>
    __dict__ = {'code': 4000, 'message': 'Invalid Client ID'}
    __dir__ = <built-in method __dir__ of DiscordError object>
    __doc__ = None
    __eq__ = <method-wrapper '__eq__' of DiscordError object>
    __format__ = <built-in method __format__ of DiscordError object>
    __ge__ = <method-wrapper '__ge__' of DiscordError object>
    __getattribute__ = <method-wrapper '__getattribute__' of DiscordError object>
    __gt__ = <method-wrapper '__gt__' of DiscordError object>
    __hash__ = <method-wrapper '__hash__' of DiscordError object>
    __init__ = <bound method DiscordError.__init__ of DiscordError('Error Code: 4000 Message: Invalid Client ID')>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of DiscordError object>
    __lt__ = <method-wrapper '__lt__' of DiscordError object>
    __module__ = 'discord_rpc.exceptions'
    __ne__ = <method-wrapper '__ne__' of DiscordError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of DiscordError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of DiscordError object>
    __repr__ = <method-wrapper '__repr__' of DiscordError object>
    __setattr__ = <method-wrapper '__setattr__' of DiscordError object>
    __setstate__ = <built-in method __setstate__ of DiscordError object>
    __sizeof__ = <built-in method __sizeof__ of DiscordError object>
    __str__ = <method-wrapper '__str__' of DiscordError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    __weakref__ = None
    args = ('Error Code: 4000 Message: Invalid Client ID',)
    code = 4000
    message = 'Invalid Client ID'
    with_traceback = <built-in method with_traceback of DiscordError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "C:\Users\Théo\AppData\Roaming\krita\pykrita\discord_rpc\discord_rpc.py", line 24, in setup
    RPC.connect()  # Start the handshake loop
  File "C:\Users\Théo\AppData\Roaming\krita\pykrita\discord_rpc\presence.py", line 45, in connect
    self.loop.run_until_complete(self.handshake())
  File "asyncio\base_events.py", line 646, in run_until_complete
  File "C:\Users\Théo\AppData\Roaming\krita\pykrita\discord_rpc\baseclient.py", line 121, in handshake
    raise DiscordError(data['code'], data['message'])
discord_rpc.exceptions.DiscordError: Error Code: 4000 Message: Invalid Client ID
```
If I close the error and open up a .kra project file, I can see that Discord is picking up Krita... but with no more information than the time I've been using Krita for this session :/
![image](https://github.com/user-attachments/assets/f64133e4-f1df-40d2-9adb-59df85923936)

I don't think I've had a Discord update since yesterday when krita-rpc still worked, so I figured maybe it was something in your plugin that the last Krita update broke..? I tried uninstalling your plugin, deactivating it in Krita, reinstalling its last version and reactivating it (and restarting Krita), but the error still seems to show up.

**Comment by tocram1** [comment]
ok i started up krita today and... everything works..???
soo maybe this is an issue on my end only and this ticket should be discarded..?
